pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                docker {
                    docker-compose build
                }
            }
        }
        stage('Deploy') {
            steps {
                docker {
                    docker-compose up -d
                }
            }
        }
    }
}

